Downgrade Quarkus à cause de java.lang.NoSuchMethodError: 'io.quarkus.bootstrap.model.PathsCollection io.quarkus.bootstrap.app.QuarkusBootstrap.getApplicationRoot()'