[.gitlab-ci.yml] Test build avec le nouveau runner et sans service Docker
Le build échoue depuis la mise à jour testcontainers 1.16.3 -> 1.19.3 avec l'erreur suivante:

[ERROR] Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: apply caps: operation not permitted: unknown"}